---
title: "Final Project RMD"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries

# Predicting Iowa housing prices through various methods

## Exploratory Data Analysis(EDA), Dependent Variable

```{r cars}
library(e1071)
library(dplyr)
library(ggplot2)
library(caretEnsemble)
library(randomForest)
library(car)
library(readr)
library(forcats)
library(magrittr)
library(xgboost)
library(Matrix)
library(gbm)
library(glmnet)

```

```{r}
Iowa_test <- read.csv('data/test.csv')
Iowa_train <- read.csv('data/train.csv')

```



```{r}
Iowa_test$SalePrice <- NA


df.combined = rbind(Iowa_train, Iowa_test)

Iowa_test$SalePrice <- as.integer(Iowa_test$SalePrice)

```


```{r}
summary(Iowa_test)
summary(Iowa_train)
```

```{r}
str(Iowa_test)
str(Iowa_train)
```

```{r}
 ggplot(data = Iowa_train, aes(Iowa_train$SalePrice) ) + geom_histogram() +labs(title = "Distribution of Sale Price", x = "Sale Price", y = "count")
```

```{r}
ggplot(data = Iowa_train, aes(x ="", y=Iowa_train$SalePrice)) + geom_boxplot() + labs(title = "Distribution of sale price", y = "Sale Price")
```

```{r}
ggplot(data = Iowa_train, aes(Iowa_train$SalePrice, fill = "grey50")) + geom_density() +labs(title = "Distribution of sale price", x = "Sale Price")
```

```{r}
 ggplot(data = Iowa_train, aes(x = "", y=Iowa_train$SalePrice) ) + geom_violin() +labs(title = "Distribution of Sale Price", y = "Sale Price")
```

# Data Cleaning
```{r}
NAcol <- which(colSums(is.na(df.combined))>0)
sort(colSums(sapply(df.combined[NAcol], is.na)), decreasing = TRUE)
```

```{r}
df.combined$Fence <- fct_explicit_na(df.combined$Fence, na_level = "None")


df.combined$Alley <- fct_explicit_na(df.combined$Alley, na_level = "None")

df.combined$LotFrontage[is.na(df.combined$LotFrontage)] <- 69.31

df.combined$GarageArea[is.na(df.combined$GarageArea)] <- 472.9

df.combined$GarageCars[is.na(df.combined$GarageCars)] <- 1.767

df.combined$PoolQC <- fct_explicit_na(df.combined$PoolQC, na_level = "None")

df.combined$MiscFeature <- fct_explicit_na(df.combined$MiscFeature, na_level = "None")

df.combined$FireplaceQu <- fct_explicit_na(df.combined$FireplaceQu, na_level = "None")

df.combined$GarageYrBlt <- as.factor(df.combined$GarageYrBlt)

df.combined$GarageYrBlt <- fct_explicit_na(df.combined$GarageYrBlt, na_level = "None")

df.combined$GarageFinish <- fct_explicit_na(df.combined$GarageFinish, na_level = "None")

df.combined$GarageQual <- fct_explicit_na(df.combined$GarageQual, na_level = "None")

df.combined$GarageCond <- fct_explicit_na(df.combined$GarageCond, na_level = "None")

df.combined$GarageType <- fct_explicit_na(df.combined$GarageType, na_level = "None")

df.combined$BsmtCond <- fct_explicit_na(df.combined$BsmtCond, na_level = "None")

df.combined$BsmtExposure <- fct_explicit_na(df.combined$BsmtExposure, na_level = "None")

df.combined$BsmtFinType1 <- fct_explicit_na(df.combined$BsmtFinType1, na_level = "None")

df.combined$BsmtFinType2 <- fct_explicit_na(df.combined$BsmtFinType2, na_level = "None")

df.combined$BsmtQual <- fct_explicit_na(df.combined$BsmtQual, na_level = "None")

df.combined$MasVnrType <- fct_explicit_na(df.combined$MasVnrType, na_level = "None")

df.combined$MasVnrArea <- as.factor(df.combined$MasVnrArea)

df.combined$MasVnrArea <- fct_explicit_na(df.combined$MasVnrArea, na_level = "None")

df.combined$PoolQC <- fct_explicit_na(df.combined$PoolQC, na_level = "None")

df.combined$MSZoning <- fct_explicit_na(df.combined$MSZoning, na_level = "None")

df.combined$Utilities <- fct_explicit_na(df.combined$Utilities, na_level = "None")

df.combined$BsmtFullBath <- as.factor(df.combined$BsmtFullBath)

df.combined$BsmtFullBath <- fct_explicit_na(df.combined$BsmtFullBath, na_level = "None")

df.combined$BsmtHalfBath <- as.factor(df.combined$BsmtHalfBath)

df.combined$BsmtHalfBath <- fct_explicit_na(df.combined$BsmtHalfBath, na_level = "None")

df.combined$Exterior1st <- fct_explicit_na(df.combined$Exterior1st, na_level = "None")

df.combined$Exterior2nd <- fct_explicit_na(df.combined$Exterior2nd, na_level = "None")

df.combined$Functional <- fct_explicit_na(df.combined$Functional, na_level = "None")

df.combined$BsmtFinSF1 <- as.factor(df.combined$BsmtFinSF1)

df.combined$BsmtFinSF1 <- fct_explicit_na(df.combined$BsmtFinSF1, na_level = "None")

df.combined$BsmtFinSF2 <- as.factor(df.combined$BsmtFinSF2)

df.combined$BsmtFinSF2 <- fct_explicit_na(df.combined$BsmtFinSF2, na_level = "None")

df.combined$SaleType <- fct_explicit_na(df.combined$SaleType, na_level = "None")

df.combined$KitchenQual <- fct_explicit_na(df.combined$KitchenQual, na_level = "None")

df.combined$Electrical <- fct_explicit_na(df.combined$Electrical, na_level = "None")

df.combined$BsmtFinSF1 <- fct_explicit_na(df.combined$BsmtFinSF1, na_level = "None")

df.combined$TotalBsmtSF <- as.factor(df.combined$TotalBsmtSF)

df.combined$TotalBsmtSF <- fct_explicit_na(df.combined$TotalBsmtSF, na_level = "None")

df.combined$BsmtUnfSF <- as.factor(df.combined$BsmtUnfSF)

df.combined$BsmtUnfSF <- fct_explicit_na(df.combined$BsmtUnfSF, na_level = "None")


```

```{r}
df.combined$GarageYrBlt <- as.integer(df.combined$GarageYrBlt)

df.combined$MasVnrArea <- as.numeric(df.combined$MasVnrArea)

df.combined$BsmtFullBath <- as.integer(df.combined$BsmtFullBath)

df.combined$BsmtHalfBath <- as.numeric(df.combined$BsmtHalfBath)

df.combined$BsmtFinSF1 <- as.numeric(df.combined$BsmtFinSF1)

df.combined$BsmtFinSF2 <- as.numeric(df.combined$BsmtFinSF2)

df.combined$TotalBsmtSF <- as.numeric(df.combined$TotalBsmtSF)

df.combined$BsmtUnfSF <- as.numeric(df.combined$BsmtUnfSF)
```

```{r}
df.combined$SalePrice = log(df.combined$SalePrice)
```



```{r}
new_Iowa_train <- df.combined[1:1460,]
new_Iowa_test <- df.combined[1461:2919,]
```


## Exploratory Data Analysis(EDA), Dependent Variable + Independent Variables

```{r}
 ggplot(data = new_Iowa_train, aes(new_Iowa_train$SalePrice) ) + geom_histogram() +facet_grid(~new_Iowa_train$MSZoning) +labs(title = "Sales Price by Zone", x = "Sale Price", y = "count")
```

```{r}
ggplot(data = new_Iowa_train, aes(x=new_Iowa_train$SalePrice)) + geom_histogram() +facet_wrap(~new_Iowa_train$MSSubClass) +labs(title = "Comparing sale price by type of dwelling", x = "Sale Price", y= "Count")
```



```{r}
ggplot(data = new_Iowa_train, aes(x=new_Iowa_train$SalePrice)) + geom_histogram() +facet_wrap(~new_Iowa_train$OverallQual) +labs(title = "Comparing sale price by overall quality", x = "Sale Price", y= "Count")
```


```{r}
ggplot(data = new_Iowa_train, aes(x=new_Iowa_train$SalePrice)) + geom_histogram() +facet_wrap(~new_Iowa_train$OverallCond) +labs(title = "Comparing sale price by Overall Condition", x = "Sale Price", y= "Count")
```

```{r}
ggplot(data = new_Iowa_train, aes(x=new_Iowa_train$SalePrice)) + geom_histogram() +facet_wrap(~new_Iowa_train$HouseStyle) +labs(title = "Comparing sale price by house style", x = "House Style", y= "Count")
```

```{r}
ggplot(data = new_Iowa_train, aes(x=new_Iowa_train$SalePrice)) + geom_histogram() +facet_wrap(~new_Iowa_train$TotRmsAbvGrd) +labs(title = "Comparing sale price by total rooms above ground", x = "Sale Price", y= "Count")
```

```{r}
ggplot(data = new_Iowa_train, aes(x=Iowa_train$SalePrice)) + geom_histogram() +facet_wrap(~new_Iowa_train$KitchenQual) +labs(title = "Comparing sale price by Kitchen Quality", x = "Sale Price", y= "Count")
```

```{r}
ggplot(data = new_Iowa_train, aes(x=new_Iowa_train$SalePrice)) + geom_histogram() +facet_wrap(~new_Iowa_train$BedroomAbvGr) +labs(title = "Comparing sale price by number of bedrooms above ground", x = "Sale Price", y= "Count")
```

```{r}
ggplot(data = new_Iowa_train, aes(x=new_Iowa_train$GrLivArea, y=new_Iowa_train$SalePrice)) + geom_point() +labs(title = "Comparing Sale Price by Ground Living Area", x = "Ground Living Area", y= "Sale Price")
```

```{r}
ggplot(data = new_Iowa_train, aes(x=new_Iowa_train$X1stFlrSF, y=new_Iowa_train$SalePrice)) + geom_point() +labs(title = "Comparing sale price by first floor square footage", x = "1st floor square footage", y= "Sale Price")
```

```{r}
ggplot(data = new_Iowa_train, aes(x=new_Iowa_train$SalePrice)) + geom_histogram() +facet_wrap(~new_Iowa_train$GarageCars) +labs(title = "Comparing sale price by Garage Car Space", x = "Sale Price", y= "Count")
```

```{r}
ggplot(data = new_Iowa_train, aes(y=new_Iowa_train$SalePrice, x=new_Iowa_train$YearRemodAdd)) + geom_point()  +labs(title = "Comparing sale price by year remodeled", x = "Year remodeled", y= "Sale Price")
```

```{r}
ggplot(data = new_Iowa_train, aes(y=new_Iowa_train$SalePrice, x=new_Iowa_train$YearBuilt)) + geom_point()  +labs(title = "Comparing sale price by year built", x = "Sale Price", y= "Year Built")
```

```{r}
ggplot(data = new_Iowa_train, aes(x=new_Iowa_train$SalePrice)) + geom_histogram() +facet_wrap(~new_Iowa_train$Neighborhood) +labs(title = "Comparing sale price by neighborhood", x = "Sale Price", y= "Count")
```

```{r}
ggplot(data = new_Iowa_train, aes(y=new_Iowa_train$SalePrice, x=new_Iowa_train$OverallQual)) + geom_point()  +labs(title = "Comparing sale price by Overall Quality", x = "Overall Quality", y= "Sale Price")
```


# Model Building

## Initial Model
```{r}
Initial_Forest = randomForest(SalePrice ~ . , data=new_Iowa_train, na.action=na.omit, importance=TRUE, mtry= 26, ntree = 1000)
```

```{r}
varImpPlot(Initial_Forest, type = 2, n.var = 20)
```

```{r}
predict_Initial <- predict(Initial_Forest, new_Iowa_test, type = "response", xlev = c("None"))
predict_Initial <- exp(predict_Initial)
submit_Initial <- data.frame(Id = new_Iowa_test$Id, SalePrice = predict_Initial)
write.csv(submit_Initial, file = "Inital_model.csv", row.names = FALSE)
```

```{r}
##Kaggle Score for this model: 2506th place, score of 0.14817
```

##Classic Linear Regression Model

```{r}
Model_1 <- lm(SalePrice ~ YearBuilt + log(GrLivArea)  + Neighborhood + GarageCars + OverallQual + TotalBsmtSF + YearRemodAdd +LotArea,  data = new_Iowa_train)


summary(Model_1)


```



```{r}
predict_linear <- predict(Model_1, new_Iowa_test, type = "response", xlev = c("None"))
predict_linear <- exp(predict_linear)
submit_linear <- data.frame(Id = new_Iowa_test$Id, SalePrice = predict_linear)
write.csv(submit_linear, file = "Linearmodel.csv", row.names = FALSE)
```

```{r}
##Kaggle placement for this model: 2593rd place, score of 0.15512
```



##Random Forest Model



```{r}



Random_Forest_Model <- randomForest(SalePrice ~ YearBuilt + LotArea + MSZoning + Neighborhood + GarageCars + OverallQual + OverallCond  + TotRmsAbvGrd +   TotalBsmtSF + Fireplaces + SaleType + HouseStyle + WoodDeckSF + GarageArea + BedroomAbvGr + FullBath + GrLivArea + Foundation + OpenPorchSF + YrSold,   data = new_Iowa_train, mtry = 7, ntree = 1000, importance = TRUE)

summary(Random_Forest_Model)

```

```{r}

predict_random_forest <- predict(Random_Forest_Model, new_Iowa_test, type = "response", xlev = c("None"))
predict_random_forest <- exp(predict_random_forest)
submit_random_forest <- data.frame(Id = new_Iowa_test$Id, SalePrice = predict_random_forest)
write.csv(submit_random_forest, file = "random_forest.csv", row.names = FALSE)


```

```{r}
##Kaggle placement for this model: 2563rd place, score of 0.14973 score of 0.14973
```

##Bagging

```{r}
house.bag <- randomForest(log(SalePrice)~ YearBuilt + LotArea + MSZoning + Neighborhood + GarageCars + OverallQual + OverallCond + TotRmsAbvGrd + TotalBsmtSF + Fireplaces + SaleType + HouseStyle + WoodDeckSF + GarageArea + BedroomAbvGr + FullBath + GrLivArea +   Foundation + OpenPorchSF + YrSold, data = new_Iowa_train, mtry=20, importance=TRUE, na.action = na.omit)

summary(house.bag)
```

```{r}
predict_bag <- predict(house.bag, new_Iowa_test, type = "response", xlev = c("None"))
predict_bag <- exp(predict_bag)
submit_bag <- data.frame(Id = new_Iowa_test$Id, SalePrice = predict_bag)
write.csv(submit_random_forest, file = "bag.csv", row.names = FALSE)
```

```{r}
##Kaggle placement for this model: 2563rd place, score of 0.14973 score of 0.14973
```


##GBM
    
    ```{r}
Iowa.boost=gbm(SalePrice ~ . ,data = new_Iowa_train,distribution = "gaussian",n.trees = 1000,
                  shrinkage = 0.01, interaction.depth = 4)
Iowa.boost

summary(Iowa.boost)
```

```{r}
predict_GBM <- predict(Iowa.boost, new_Iowa_test, type = "response", xlev = c("None"), n.trees=1000)
predict_GBM <- exp(predict_GBM)
submit_GBM <- data.frame(Id = new_Iowa_test$Id, SalePrice = predict_GBM)
write.csv(submit_GBM, file = "GBM.csv", row.names = FALSE)
```

```{r}
##Kaggle placement for this model: 1296th place, score of 0.12626
```

##Lasso
```{r}
set.seed(123)
cv_lasso = cv.glmnet(as.matrix(Training[, -59]), Training[, 59])

## Predictions
preds <- predict(cv_lasso, newx = as.matrix(new -59]), s = "lambda.min")
rmse(Validation$SalePrice, preds)78
```


```{r}
#SalePrice ~ YearBuilt + LotArea + MSZoning + Neighborhood + GarageCars + OverallQual + OverallCond  + TotRmsAbvGrd +   TotalBsmtSF + Fireplaces + SaleType + HouseStyle + WoodDeckSF + GarageArea + BedroomAbvGr + FullBath + GrLivArea + Foundation + OpenPorchSF + YrSold
```



```{r}
#X2 <- data.matrix(new_Iowa_train[1:1459,1:80], rownames.force = NA)
#1 <- new_Iowa_train[,81]
```

```{r}
#Lasso_model <- glmnet(x = X2, y = y1, alpha = 1)


```

```{r}
#Lasso_Data_frame <- Lasso_model
```

```{r}

```

```{r}

#lasso.pred <- predict(Lasso_model, newx, s = 0.01)
#lasso.pred <- exp(lasso.pred)
#submit_Lasso <- data.frame(Id = new_Iowa_test$Id, SalePrice = lasso.pred)
#write.csv(lasso.pred, file = "Lasso.csv", row.names = FALSE)
```

```{r}
X.train <- model.matrix(SalePrice ~ ., data = new_Iowa_train)
y.train <- new_Iowa_train$SalePrice

X.test <- model.matrix(SalePrice ~., data = new_Iowa_test)
y.test <- new_Iowa_test$SalePrice
```

```{r}
grid <- 10^seq(10, -2, length = 100)
credit.ridge <- glmnet(X.train, y.train, alpha = 0, lambda = grid)
```

```{r}
Iowa.lasso <- glmnet(X.train, y.train, lambda = grid, alpha = 1)
```

```{r}
set.seed(55)
cv.out.lasso <- cv.glmnet(X.train, y.train, lambda = grid, alpha = 1)
```

```{r}
bestlam.lasso <- cv.out.lasso$lambda.min
bestlam.lasso
```

```{r}
Iowa.lasso.pred.bestlam <- predict(Iowa.lasso, s = bestlam.lasso, newx = X.test)
summary(Iowa.lasso.pred.bestlam)
```

